### ISSUE TITLE
Requirements installation problem

### ISSUE THREAD

**Issue by kate-holdener** [rjuliang/Scantron_Software#31]
When installing requirements.txt I got the following error:
```
ERROR: Could not find a version that satisfies the requirement poppler (from versions: none)
ERROR: No matching distribution found for poppler
```
I was able to install python-poppler instead of poppler.

**Comment by kate-holdener** [comment]
Additional problem encountered after installing requirements.txt:
```
python3 get_file.py 
Traceback (most recent call last):
  File "/Users/holdenerea/repos/Scantron_Software/back-end python/get_file.py", line 1, in <module>
    from flask import Flask, jsonify, request, send_file, send_from_directory
ModuleNotFoundError: No module named 'flask'
```

I ran: ```pip3 install Flask```, which resolved that issue. I wonder if it's an OS difference (I'm on a Mac).

After that, the problem was:
```
python3 get_file.py 
Traceback (most recent call last):
  File "/Users/holdenerea/repos/Scantron_Software/back-end python/get_file.py", line 2, in <module>
    from flask_cors import CORS, cross_origin
ModuleNotFoundError: No module named 'flask_cors
```
I worked around it with: pip install flask_cors

**Comment by Annoyed-Raven** [comment]
@kate-holdener @aaronbi 
Yes poppler is a weird need that is installed differently based on os, macs and Linux have the ability to install from a command but Windows needs a downloaded version and installed to path. We weren't sure the best way to approach this yet. We are meetings Sunday/Monday to work on some of these issues.
