### ISSUE TITLE
Provide example CSV answer key format

### ISSUE THREAD

**Issue by kate-holdener** [rjuliang/Scantron_Software#32]
I'm trying out your software and need to upload an answer key in CSV format as well as a pdf of the student answers. I found an example pdf in your repo. Please provide an example answer key csv file.

**Comment by Annoyed-Raven** [comment]
@rjuliang we need to be able to accept the csv file for the test key

**Comment by Annoyed-Raven** [comment]
We can have the answer key go to the same location as the current scantron
file that is submitted.
